# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 00:05
from __future__ import unicode_literals

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund', models.CharField(default=0, max_length=100, verbose_name='余额')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='电话')),
                ('fund', models.CharField(default=0, max_length=100, verbose_name='余额')),
                ('store_status', models.BooleanField(default=False, verbose_name='商店状态')),
                ('address', models.CharField(blank=True, max_length=40, verbose_name='地址')),
            ],
        ),
        migrations.CreateModel(
            name='UserAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('password', models.TextField()),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('avatar', models.ImageField(blank=True, default='timg.jpg', upload_to=account.models.user_dictionary_path, verbose_name='头像')),
                ('identity', models.CharField(choices=[('s', '商家'), ('c', '买家')], max_length=1, null=True, verbose_name='身份')),
            ],
        ),
        migrations.AddField(
            model_name='seller',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.UserAll'),
        ),
        migrations.AddField(
            model_name='customer',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.UserAll'),
        ),
    ]
