# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='3aa873c0fbcc11e8a3cb54e1adb1338e', max_length=50, verbose_name='单号')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
                ('number', models.CharField(default=1, max_length=100, verbose_name='购买个数')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Goods')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Seller')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='内容')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
                ('reply_id', models.IntegerField(default=0)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_good', to='shop.NewestGoods')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_writer', to='account.UserAll')),
            ],
        ),
    ]
