# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='8749ce74fbcc11e89b4b54e1adb1338e', max_length=50, verbose_name='单号'),
        ),
    ]
