# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0003_auto_20181210_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='94f41c9dfd0c11e8ae9654e1adb1338e', max_length=50, verbose_name='单号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_receiver', to='account.Seller'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_sender', to='account.Customer'),
        ),
    ]
