# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0005_auto_20181211_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='f98c92c286ad4384a80352ef237483aa', max_length=50, verbose_name='单号'),
        ),
    ]
