# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-26 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0007_auto_20181211_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(max_length=50, verbose_name='单号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_good', to='shop.Goods', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_receiver', to='account.Seller', verbose_name='商家'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_sender', to='account.Customer', verbose_name='购买方'),
        ),
    ]
