# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='fake_id',
            field=models.CharField(default=uuid.UUID('87490b8c-fbcc-11e8-b511-54e1adb1338e'), max_length=100),
        ),
    ]
