# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20181210_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='fake_id',
            field=models.CharField(default=uuid.UUID('94f41c9c-fd0c-11e8-8f7b-54e1adb1338e'), max_length=100),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='newestgoods',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格'),
        ),
    ]
