# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20181211_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='fake_id',
            field=models.CharField(default=uuid.UUID('9b9c975e-fd0d-11e8-9311-54e1adb1338e'), max_length=100),
        ),
    ]
