# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20181211_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='fake_id',
            field=models.CharField(default=uuid.UUID('b11d8e65-c608-4a4a-b1dc-d9282cc580d9'), max_length=100),
        ),
    ]
