# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20181211_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newestgoods',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': '购物车', 'verbose_name_plural': '购物车'},
        ),
        migrations.RemoveField(
            model_name='newestgoods',
            name='praise',
        ),
        migrations.AlterField(
            model_name='goods',
            name='fake_id',
            field=models.CharField(default=uuid.UUID('8e39e296-e7cb-44da-b6a8-107070a95b31'), max_length=100),
        ),
        migrations.AlterField(
            model_name='newestgoods',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='account.Seller', verbose_name='所属商家'),
        ),
    ]
