# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-14 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20181213_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='fake_id',
            field=models.CharField(default='73be2400-ffa2-11e8-ad26-54e1adb1338e', max_length=100),
        ),
    ]
