# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-26 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20181214_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='fake_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goods',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
